### ISSUE TITLE
Names of hospitalization and ICU metrics

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDataProcess#48]
Some districts (e.g., YT) provide only cumulative hospitalization metrics, as opposed to the traditional current hospitalization metrics. These are presently called "hospitalizations_cum" and "hospitalizations", but perhaps they should be renamed to "hospitalizations_total" and "hospitalizations_current" or "hospitalizations_active"?

**Comment by kbelisar** [comment]
Initially this seemed confusing in the context of processing these data. However, as much as I think this is a good distinction to make as the metrics become increasingly complex, this naming convention makes sense for the end user. Specifically, the absence of a suffix to denote active data, and the use of a `_cum` suffix for any cumulative metric across data domains. If there are distinctions between active counts versus new counts, then likewise these require standardized suffixes.

**Comment by jeanpaulrsoucy** [comment]
Thanks for your feedback. In that case, we'll keep the names as-is for now and perhaps revisit after #49 is complete.
